fix(core): update core config file and handle read errors
forcedotcom/lightning-language-server pull request #558
Opened 2023-04-10 13:44 UTC by mpsenn

The core config file containing environment variables is now build/dev.properties. Use that file instead of config.blt. Additionally handle any errors in parsing and reading by logging to console and not attempting to write to the file.

This change is not yet tested.

2023-04-10 13:46 UTC, mpsenn commented
Fixes #497.

2023-04-10 20:14 UTC, mpsenn commented
Note: for git checkout of core, this generates settings with empty p4.port values, etc. This is fine, I think the eslint executable is what really matters.

2023-04-10 21:02 UTC, jasonschroeder-sfdc approved these changes

2023-04-12 15:36 UTC, randi274 requested changes
QA looks good! For our SFDX users, we see the language server boots up as expected, and the usual functionality like hover, go-to-definition and auto-complete work great.

I am seeing some failing tests in our internal PR, and they're reproducible locally. Likely just a stubbing issue that needs to be updated given the new path. Let me know when you're able to take a look and I'll get the updated changes merged into my branch. Thanks!

https://github.com/forcedotcom/lightning-language-server/actions/runs/4680070576/jobs/8290938179

2023-04-12 20:17 UTC, mpsenn commented
@randi274 I've updated the change, after taking a closer look at a colleague's setup, it looks like env. variables are used for the config now instead of a properties file. So I've updated the implementation, and modified the test workspace to match.

2023-04-14 16:36 UTC, closed without merging

2023-04-14 17:23 UTC, randi274 commented
Thanks again @mpsenn! We'll get this updated in vs code ASAP 🎉